### ISSUE TITLE
Does the bot skip the post if it is already liked or commented?

### ISSUE THREAD

**Issue by ammarahm-ed** [drbuche/InstaBot#1]
Can we check if the user has already liked/commented on a post and skip it after it is opened? Could such a feature be added? this would be really helpful.

**Comment by drbuche** [comment]
I had thought of that! hehe 🤣

I got it here and I will commit!

Thank you very much for evaluating my code, I started programming this month, having this feedback gives me more encouragement!

**Comment by drbuche** [comment]
DONE! Another day I will refactor to make it cleaner! 😁

**Comment by ammarahm-ed** [comment]
Also I have noticed that sometimes the generated comment only includes x, y or z and not a combination of xy, yz, or xz. 

One more suggestion would be to put the bot to sleep for a random amount of time and be able to choose random action for every post, lets say on first post it likes, on second it will comment, on another it will like and comment and so on. I think this way it will be more human. 

If the bot interacts for 15 minutes with 2 to 3 minutes sleep between each interaction, we get an average of 6 to 7 interactions after which the bot can go sleep from 5 to 15 minutes again then continue. I am not sure how safe this would be but as long as the amount of interactions are very slow, instagram cannot detect it.

**Comment by drbuche** [comment]
About the combination xy, xz, etc ... I'm having problems with Chrome, this doesn't usually happen in firefox = /

**Comment by drbuche** [comment]
I'll add this new random + sleep mode to the list of new features! Thank you!

**Comment by ammarahm-ed** [comment]
And I also noticed that since I ran the bot last night, I cannot open the hashtag page for some reason, it always shows error 501 on chrome. I will try this with firefox and see what happens there. I am running this on mac.

**Comment by drbuche** [comment]
I've been having this problem with hashtags since yesterday! I've tried to log into other computers and other accounts, but .... the problem continues, I think it might be something from Instagram... My friends are having the same problem ...

**Comment by drbuche** [comment]
https://www.reddit.com/r/Instagram/comments/isvpu9/explore_page_not_working_on_browser/

https://downdetector.com/status/instagram/

🤔

**Comment by ammarahm-ed** [comment]
I hope its not down for forever Lol.

**Comment by ammarahm-ed** [comment]
Seems like the hashtags page is working again.

**Comment by drbuche** [comment]
Finally 🙌🏻 hahahaha

**Comment by ammarahm-ed** [comment]
It seems like commenting is not working after the new changes. Only likes. Maybe there are more than one `a` tags with the username as value in the document. So even if there is no comment by the user, it can still find a value and return true

**Comment by drbuche** [comment]
- Like + comment mode - makes the first comment after giving 10 likes

- like mode - just 'like' every 1-2 min

- Comment mode - only comments every 6 to 10 minutes

it's working here = /

Arriving home, I will test on the other computers.

(but I only tested it on Firefox)

**Comment by ammarahm-ed** [comment]
Yes its working, I am using firefox now. Works better I guess
