### ISSUE TITLE
Likes

### ISSUE THREAD

**Issue by Janncrl** [drbuche/InstaBot#7]
Os likes nao estao funcionando, apenas os comentários funcionam.. mas parece que desaparecem ao fim de uns segundos..

**Comment by drbuche** [comment]
Já tentou outro webdriver?normalmente Firefox tem se saído muito bem

Verificou se selecionou a linguagem do navegador corretamente?
Dependendo da linguagem do navegador os nomes de botões mudam (ex: like para curtir)

De qualquer forma, vou ver com alguns colegas se alguém apresentou algum problema hoje 👍🏻

**Comment by drbuche** [comment]
Testei aqui. (em 3 pcs da minha casa e um colega no computador do trabalho)
Tudo rodando normalmente, tente verificar os pontos que falei no ultimo post

Outro fator que pode causar o ato de você dar like e comentar e ‘desaparecer’ após alguns segundos é uma restrição do instagram, isso ocorre se você usar o bot por um período muito longo de tempo sem pausas, como uma pessoa real não faria.

Além disso não indico usar o instagram enquanto o bot roda, isso pode causar alguns problemas.

**Comment by Janncrl** [comment]
O problema é da linguagem do navegador, que esta em pt pt, mas mesmo após a alteração da linguagem cada vez que o bot inicia o navegador a linguagem volta a estar em pt pt.. quais os ficheiros que contem essa informaçao para alterar para pt pt ?

Obrigado

**Comment by drbuche** [comment]
Isso deveria ser alterado no momento que o bot esta rodando, quando ele faz a ultima pergunta "Qual o idioma do seu navegador?" e você digita 1 para pt e 2 para en

a partir desse input ele faz a seleção da linguagem no atributo construtor no modulo https://github.com/drbuche/InstaBot/blob/master/instabot/bot.py  e ja roda automaticamente

**Comment by Janncrl** [comment]
Mesmo que a linguagem esteja em pt de portugal ?

**Comment by drbuche** [comment]
Boa pergunta, hehe, não tenho certeza, o pt atual do programa é pt-br, não sei se o nome das variaves são iguais em Portugal. 
Você pode abrir a pagina do instagram e procurar as referencias no codigo fonte da pagina, caso sejam diferentes da pt-br é so alterar no modulo bot.py

**Comment by drbuche** [comment]
Achei, só mudar no modulo bot.py

            self.like = 'Gosto'
            self.post = 'Publicar'
            self.unlike = 'Não gosto'

Esses são os termos em pt-portugal

**Comment by Janncrl** [comment]
Ja tinha encontrado eheh, funcionando perfeitamente. Agradecido pela ajuda..

**Comment by drbuche** [comment]
SHOW!

**Comment by drbuche** [comment]
Só continuar acompanhando que sempre estou colocando novos recursos.
