### ISSUE TITLE
Where define chromedriver?

### ISSUE THREAD

**Issue by Individuum92** [drbuche/InstaBot#9]
Hi,

when i run the main script I revieved following error:

```
line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

Where can I set the Path to the chromedriver?

**Comment by ghost** [comment]
> Oi,
> 
> ao executar o script principal, obtive o seguinte erro:
> 
> ```
> line 83, in start
>     os.path.basename(self.path), self.start_error_message)
> selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
> ```
> 
> Onde posso definir o caminho para o chromedriver?

Olá, vc resolveu seu problema?

**Comment by gpedro** [comment]
for linux, add that on .bashrc or .profile:
`export PATH=$PATH:/path/where/is/located/chromedriver/file`

for windows,
https://www.browserstack.com/guide/run-selenium-tests-using-selenium-chromedriver#toc1
